<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reserva2.BE\Reserva2.BE.csproj" />
    <ProjectReference Include="..\Reserva2.BLL\Reserva2.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="frmLogin.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Comercios\" />
    <Folder Include="Elementos\" />
    <Folder Include="Dispobilidad\" />
    <Folder Include="Auditoria\" />
    <Folder Include="Pagos\" />
    <Folder Include="Reservas\" />
    <Folder Include="Usuarios\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>