<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reserva2.BE\Reserva2.BE.csproj" />
    <ProjectReference Include="..\Reserva2.BLL\Reserva2.BLL.csproj" />
  </ItemGroup>

</Project>